sudo: true
language: ruby
env:
  - DB=sqlite RAILS_TRV=514
  - DB=mysql RAILS_TRV=514
  - DB=postgresql RAILS_TRV=514
addons:
  postgresql: "9.6"
services:
  - postgresql
  - mysql
rvm:
  - 2.5.0
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libvirt-dev
  - psql -c 'CREATE DATABASE foreman;' -U postgres
  - mysql -e 'CREATE DATABASE foreman;'
  - cp config/settings.yaml.travis config/settings.yaml
  - cp config/database.yml.travis config/database.yml
  - gem update --system
bundler_args: --jobs=3 --retry=3 --without=development
script:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install --unsafe-perm
  - AS_DEPRECATION_RECORD=yes VERBOSE=false QUIET=true rake db:migrate RAILS_ENV=development
  - AS_DEPRECATION_RECORD=yes NOTIFICATIONS_POLLING=1000000 rake jenkins:unit
  - 'if [ "$DB" != "sqlite" ]; then AS_DEPRECATION_RECORD=yes NOTIFICATIONS_POLLING=1000000 rake jenkins:integration; fi'
